#!/usr/bin/env python3
"""Generate migration-028.sql (last_year_sales) from the owner's daily sales CSV.

Usage: python3 scripts/ly-csv-to-migration.py ~/Desktop/bllastyearsales.csv > migration-028.sql

CSV shape: business_date, store_channel ("Store - Retail|Bins"), gross_sales,
discounts, refunds, net_sales. One row per store/channel/day. We pivot the two
channels into one row per store-day using net_sales (per the owner: net).

Store name -> dashboard store code (cardCode = STORES[i].split('/')[0]).
"Indy" is Wyoming-era data reused for Indy East (BL16) — owner approved.
"""
import csv, sys, collections

MAP = {
    'Coliseum': 'BL1',
    'South Bend': 'BL2',
    'Dupont': 'BL4',
    'Holland': 'BL8',
    'Battle Creek': 'BL14',
    'Indy': 'BL16',
}

def main(path):
    days = collections.defaultdict(lambda: {'retail': 0.0, 'bin': 0.0})
    unknown = collections.Counter()
    with open(path, newline='') as f:
        for r in csv.DictReader(f):
            name, _, channel = r['store_channel'].rpartition(' - ')
            code = MAP.get(name)
            if not code:
                unknown[r['store_channel']] += 1
                continue
            ch = 'retail' if channel == 'Retail' else 'bin' if channel == 'Bins' else None
            if ch is None:
                unknown[r['store_channel']] += 1
                continue
            days[(code, r['business_date'])][ch] += float(r['net_sales'] or 0)
    if unknown:
        print(f"-- WARNING unmapped store_channel values: {dict(unknown)}", file=sys.stderr)
        sys.exit(1)

    rows = sorted(days.items())
    dates = sorted(d for (_, d) in days)
    print("-- migration-028: last-year daily net sales (retail/bin) for the store-card")
    print("-- 'vs last year' comparison. Generated by scripts/ly-csv-to-migration.py")
    print(f"-- from bllastyearsales.csv — {len(rows)} store-days, "
          f"{dates[0]} → {dates[-1]}. 'Indy' rows are Wyoming-era data")
    print("-- deliberately mapped to BL16 (owner approved).")
    print("CREATE TABLE IF NOT EXISTS last_year_sales (")
    print("  store  TEXT NOT NULL,")
    print("  date   TEXT NOT NULL,")
    print("  retail REAL NOT NULL DEFAULT 0,")
    print("  bin    REAL NOT NULL DEFAULT 0,")
    print("  PRIMARY KEY (store, date)")
    print(");")
    BATCH = 50
    for i in range(0, len(rows), BATCH):
        chunk = rows[i:i + BATCH]
        vals = ",\n".join(
            f"('{code}','{date}',{v['retail']:.2f},{v['bin']:.2f})"
            for (code, date), v in chunk
        )
        print(f"INSERT OR REPLACE INTO last_year_sales (store,date,retail,bin) VALUES\n{vals};")
    print(f"-- {len(rows)} rows total", file=sys.stderr)

if __name__ == '__main__':
    main(sys.argv[1])
